name: NT Employment Mentors Network
favicon: null
layout_spectrum: 0.0088
typography_spectrum: 0.2995740631595254
title: NT Employment Mentors Network
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72902203-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fda617'
    - '#e78200'
    - '#eccb74'
    - '#f4e0ab'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
