typography_spectrum: 0.6585336874704808
color:
  brandColors:
    - '#ffffff'
    - '#fda617'
    - '#e78200'
    - '#eccb74'
    - '#f4e0ab'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.08057508058845997
analytics:
  google: UA-72902203-3
  facebook: null
  twitter: null
name: NT Employment Mentors Network
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: NT Employment Mentors Network
purpose: []
