name: NT Employment Mentors Network
favicon: null
layout_spectrum: 0.3258
typography_spectrum: 0.2995740631595254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fda617'
    - '#e78200'
    - '#eccb74'
    - '#f4e0ab'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
