layout_spectrum: 0.8005125417839736
typography_spectrum: 0.2615376024041325
color:
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
  brandStrength: 0.7079125235322863
  lightness: 0.5270069092512131
  saturation: 0.8749012826010585
  rhythmicContrast: 0.4691767825279385
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-72902203-3
  facebook: null
  twitter: null
name: NT Employment Mentors Network
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: NT Employment Mentors Network
purpose: []
